ID: q0ssc4wgdfxp0jkcoa25h6afnh4wqd1i
"\uB370\uC774\uD130\uACBD\uB85C": "original_data\\q0ssc4wgdfxp0jkcoa25h6afnh4wqd1i\\\
  \uAE30\uC5C5CB_sample.csv"
"\uB370\uC774\uD130\uC14B\uBA85": "\uAE30\uC5C5 CB  \uC0D8\uD50C"
