번호: 1
카테고리: 기업CB합성
알고리즘: CART
학습명: 기업CB_합성데이터셋생성 v0.1
데이터셋ID: q0ssc4wgdfxp0jkcoa25h6afnh4asdfz
학습셋길이: 6000
테스트셋길이: 1000
이전학습: ''
등록자: system
수행시작일자: '2019-01-28 20:26:31'
수행종료일시: '2019-01-28 20:28:55'
결과(Accuracy): 0.9820
상태: 정상종료
공개범위: 전체공개
초기화방법: Xavier uniform
최적화방법: Adam
자동저장주기: 50
배치사이즈: 0
learning-rate: 0.01
dropout: 0.1
epochs: 50